### ISSUE TITLE
Kompabilitet med GnuCash import

### ISSUE THREAD

**Issue by CirruZZ** [buffis/swedbank-qif-export#2]
Hittade ditt förnämliga tillägg, tackar för att du delar!!

Körde det med GnuCash men funkade inte, beroende på att det vara mellanslag i summor över 1000kr , ex 1 000.

Ändrade  rad 30 i contentscript.js

`"T" + input["amount"].replace(",", ".") + "\n" +`

till

`"T" + input["amount"].replace(",", ".").replace(" ", "") + "\n" +`

kollade och inga problem med YNAB heller. :-)

**Comment by buffis** [comment]
Kul att det uppskattas!

Har själv inte använt det här på ett litet tag faktiskt, men alltid roligt att fler har användning av det :)

Fixar på en gång!

Tar gärna emot pull requests om du har andra förslag på förbättring också.
